file_exists_behavior: OVERWRITE
files: 
  - 
    destination: /var/www/cloudparking
    source: /
os: linux
trigger: 
  branches: 
    include: 
      - main
      - releases/*
  paths: 
    exclude: 
      - /public/.htaccess
    include: ~
version: 0.0
    
